### ISSUE TITLE
complete the cert manager + external dns integration

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x-labs/issues#13]
we may needd to modify the default external dns https://github.com/jenkins-x-labs/jenkins-x-versions/blob/master/apps/bitnami/external-dns/values.yaml.gotmpl and cert manager binding files https://github.com/jenkins-x-labs/jenkins-x-versions/blob/master/apps/jetstack/cert-manager/values.yaml.gotmpl 

we should also turn the acme chart into a real separate chart as well so it can be easily added to the `jx-apps.yml` https://github.com/jenkins-x/jenkins-x-boot-config/tree/master/systems/acme

**Comment by jstrachan** [comment]
we've got an acme chart now so something like this in your `jx-apps.yml` should enable acme, cert manager and external dns:
```yaml 
apps:
- name: stable/nginx-ingress
- name: jetstack/cert-manager
- name: jenkins-x/acme
- name: bitnami/externaldns
...
```
