### ISSUE TITLE
jxl project and possibly also jxl import creates SourceRepository object conflicting with dev environment helmfile

### ISSUE THREAD

**Issue by gazal-k** [jenkins-x-labs/issues#16]
`jxl project` creates a quickstart and triggers the first pipeline for it.
It creates the `SourceRepository` object and also adds a `SourceRepository` definition in the dev env repo.

repositories/templates/github-org-golang-helm3-sr.yaml
```yaml
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: github-org
    provider: github
    repository: golang-helm3
  name: github-org-golang-helm3
spec:
  description: Imported application for github-org/golang-helm3
  httpCloneURL: https://github.com/github-org/golang-helm3.git
  org: github-org
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: golang-helm3
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/github-org/golang-helm3.git
```

When we try to merge the PR for the dev env repo, it will fail because the `SourceRepository` already exists
